<a href="https://colab.research.google.com/github/fathinzts/implementation-SVM-Method-with-Google-Collabs/blob/main/SVM_TAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!unrar x "/content/drive/MyDrive/Klasifikasi_Glaukoma.rar" "/content/drive/MyDrive/Colab Notebooks"


UNRAR 5.50 freeware      Copyright (c) 1993-2017 Alexander Roshal


Extracting from /content/drive/MyDrive/Klasifikasi_Glaukoma.rar


Would you like to replace the existing file /content/drive/MyDrive/Colab Notebooks/otsu with adaptive threshold graybiasa r2.csv
209477 bytes, modified on 2021-12-11 05:40
with a new one
209477 bytes, modified on 2021-12-11 05:40

[Y]es, [N]o, [A]ll, n[E]ver, [R]ename, [Q]uit y

Extracting  /content/drive/MyDrive/Colab Notebooks/otsu with adaptive threshold graybiasa r2.csv      73%  OK 

Would you like to replace the existing file /content/drive/MyDrive/Colab Notebooks/otsu with adaptive threshold graybiasa r3.csv
 71538 bytes, modified on 2021-12-11 01:49
with a new one
 71538 bytes, modified on 2021-12-11 01:49

[Y]es, [N]o, [A]ll, n[E]ver, [R]ename, [Q]uit y

Extracting  /content/drive/MyDrive/Colab Notebooks/otsu with adaptive threshold graybiasa r3.csv      99%  OK 
All OK


In [ ]:
import pandas as pd
import numpy as np
#Import svm model
from sklearn import svm
#Import scikit-learn metrics module for accuracy calculation
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
data1 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/otsu with adaptive threshold graybiasa r2.csv')
data2 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/otsu with adaptive threshold graybiasa r3.csv')

In [ ]:
data1.head()

filename  contrast_00  contrast_45  ...  entropi_histo  kehalusan_histo  class
0  Im001.jpg   149.606823   215.059943  ...       0.712210         0.023174      0
1  Im002.jpg   135.504058   165.931589  ...       0.784095         0.020716      0
2  Im003.jpg   138.991817   188.015883  ...       0.674531         0.018570      0
3  Im004.jpg   146.851973   197.595799  ...       0.816202         0.025967      0
4  Im005.jpg   140.774381   184.286932  ...       0.731381         0.022625      0

[5 rows x 28 columns]

In [ ]:
data2.head()

filename  contrast_00  contrast_45  ...  entropi_histo  kehalusan_histo  class
0   N-1-L.jpg   106.062163   161.083679  ...       0.980190         0.018567      0
1  N-10-R.jpg    73.325418   107.080816  ...       0.868891         0.012469      0
2  N-11-L.jpg    39.621873    63.089339  ...       0.838551         0.009985      0
3  N-13-L.jpg    48.203523    73.484748  ...       0.792173         0.010972      0
4  N-14-R.jpg   113.829900   175.655865  ...       0.894857         0.018977      0

[5 rows x 28 columns]

In [ ]:
print("data1 R2: ",(len(data1)))
print("data2 R3: ",(len(data2)))

data1 R2:  405
data2 R3:  138


In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
#data 1
train1, test1 = train_test_split(data1, test_size=0.3, random_state=5)
print("jumlah data test:", len(test1))
print("jumlah data train:", len(train1))

jumlah data test: 122
jumlah data train: 283


In [ ]:
#ALL GLCM Data1
data_feature_testing = test1[['contrast_00','contrast_45','contrast_90','contrast_135','IDM_00','IDM_45','IDM_90','IDM_135','entropy_00','entropy_45','entropy_90','entropy_135','corellation_00','corellation_45','corellation_90','corellation_135','energy_00','energy_45','energy_90','energy_135']]
data_feature_training = train1[['contrast_00','contrast_45','contrast_90','contrast_135','IDM_00','IDM_45','IDM_90','IDM_135','entropy_00','entropy_45','entropy_90','entropy_135','corellation_00','corellation_45','corellation_90','corellation_135','energy_00','energy_45','energy_90','energy_135']]
data_class_training = train1['class']
data_class_testing = test1['class']

In [ ]:
#Create a svm Classifier
clf = svm.SVC(kernel='linear')

#Train the model using the training sets
clf.fit(data_feature_training, data_class_training)

#Predict the response for test dataset
y_pred = clf.predict(data_feature_testing)

# print(confusion_matrix(y_test,y_pred))
print(classification_report(data_class_testing,y_pred))
print(confusion_matrix(data_class_testing,y_pred))

              precision    recall  f1-score   support

           0       0.63      0.90      0.74        68
           1       0.72      0.33      0.46        54

    accuracy                           0.65       122
   macro avg       0.67      0.62      0.60       122
weighted avg       0.67      0.65      0.61       122

[[61  7]
 [36 18]]


In [ ]:
#ALL Historgram Data1
data_feature_testing = test1[['intensitas_histo','standar_dev_histo','skewness_histo','energi_histo','entropi_histo','kehalusan_histo']]
data_feature_training = train1[['intensitas_histo','standar_dev_histo','skewness_histo','energi_histo','entropi_histo','kehalusan_histo']]
data_class_training = train1['class']
data_class_testing = test1['class']

In [ ]:
#Create a svm Classifier
clf = svm.SVC(kernel='linear')

#Train the model using the training sets
clf.fit(data_feature_training, data_class_training)

#Predict the response for test dataset
y_pred = clf.predict(data_feature_testing)

# print(confusion_matrix(y_test,y_pred))
print(classification_report(data_class_testing,y_pred))
print(confusion_matrix(data_class_testing,y_pred))

              precision    recall  f1-score   support

           0       0.67      0.90      0.77        68
           1       0.77      0.44      0.56        54

    accuracy                           0.70       122
   macro avg       0.72      0.67      0.67       122
weighted avg       0.72      0.70      0.68       122

[[61  7]
 [30 24]]


In [ ]:
#data 2
train2, test2 = train_test_split(data2, test_size=0.3, random_state=5)
print("jumlah data test:", len(test2))
print("jumlah data train:", len(train2))

jumlah data test: 42
jumlah data train: 96


In [ ]:
data_feature_testing = test2[['contrast_00','contrast_45','contrast_90','contrast_135','IDM_00','IDM_45','IDM_90','IDM_135','entropy_00','entropy_45','entropy_90','entropy_135','corellation_00','corellation_45','corellation_90','corellation_135','energy_00','energy_45','energy_90','energy_135']]
data_feature_training = train2[['contrast_00','contrast_45','contrast_90','contrast_135','IDM_00','IDM_45','IDM_90','IDM_135','entropy_00','entropy_45','entropy_90','entropy_135','corellation_00','corellation_45','corellation_90','corellation_135','energy_00','energy_45','energy_90','energy_135']]
data_class_training = train2['class']
data_class_testing = test2['class']

In [ ]:
#Create a svm Classifier
clf = svm.SVC(kernel='linear')

#Train the model using the training sets
clf.fit(data_feature_training, data_class_training)

#Predict the response for test dataset
y_pred = clf.predict(data_feature_testing)

# print(confusion_matrix(y_test,y_pred))
print(classification_report(data_class_testing,y_pred))
print(confusion_matrix(data_class_testing,y_pred))

              precision    recall  f1-score   support

           0       0.69      0.89      0.77        27
           1       0.57      0.27      0.36        15

    accuracy                           0.67        42
   macro avg       0.63      0.58      0.57        42
weighted avg       0.64      0.67      0.63        42

[[24  3]
 [11  4]]


In [ ]:
#ALL Historgram Data2
data_feature_testing = test2[['intensitas_histo','standar_dev_histo','skewness_histo','energi_histo','entropi_histo','kehalusan_histo']]
data_feature_training = train2[['intensitas_histo','standar_dev_histo','skewness_histo','energi_histo','entropi_histo','kehalusan_histo']]
data_class_training = train2['class']
data_class_testing = test2['class']

In [ ]:
#Create a svm Classifier
clf = svm.SVC(kernel='linear')

#Train the model using the training sets
clf.fit(data_feature_training, data_class_training)

#Predict the response for test dataset
y_pred = clf.predict(data_feature_testing)

# print(confusion_matrix(y_test,y_pred))
print(classification_report(data_class_testing,y_pred))
print(confusion_matrix(data_class_testing,y_pred))

              precision    recall  f1-score   support

           0       0.64      1.00      0.78        27
           1       0.00      0.00      0.00        15

    accuracy                           0.64        42
   macro avg       0.32      0.50      0.39        42
weighted avg       0.41      0.64      0.50        42

[[27  0]
 [15  0]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
